export {
  AlignmentDiagnosticsPanel,
  type AlignmentDiagnosticsSkippedItem,
} from "./AlignmentDiagnosticsPanel";
export { AlignmentRepairEditor } from "./AlignmentRepairEditor";
export {
  ALIGNMENT_REPAIR_SCHEMA_VERSION,
  addAlignmentRepairOperation,
  alignmentRepairMapStaleness,
  alignmentRepairOperationLabel,
  alignmentRepairSummary,
  createAlignmentRepairMap,
  parseAlignmentRepairMap,
  serializeAlignmentRepairMap,
  type AlignmentRepairBoundary,
  type AlignmentRepairContext,
  type AlignmentRepairMap,
  type AlignmentRepairOperation,
  type AlignmentRepairOperationKind,
  type AlignmentRepairStaleReport,
} from "./alignmentRepairModel";
export {
  ReadAlongClock,
  startReadAlongPlaybackClock,
  type ReadAlongClockReason,
  type ReadAlongClockRuntime,
  type ReadAlongClockTick,
  type ReadAlongPlaybackClockOptions,
} from "./ReadAlongClock";
export {
  alignmentQualityLabel,
  alignmentStatusFromReport,
  type AlignmentStatus,
  type AlignmentStatusTone,
} from "./alignmentStatus";
export {
  HighlightRenderer,
  renderHighlightTextOrFallback,
  splitHighlightText,
  type HighlightRendererProps,
  type HighlightRendererToken,
  type HighlightRendererWordState,
} from "./HighlightRenderer";
export {
  normalizeAnchorText,
  readAlongAnchorForBlock,
  readAlongAnchorForWord,
  readAlongAnchorId,
  readAlongAnchorSelectors,
  resolveReadAlongDomAnchor,
  type ReadAlongDomAnchor,
  type ReadAlongResolvedDomAnchor,
} from "./domAnchorResolver";
export {
  ReadAlongResyncController,
  resolveReadAlongRuntimeSnapshot,
  type ReadAlongResyncInput,
  type ReadAlongResyncOptions,
} from "./ReadAlongResyncController";
export {
  READ_ALONG_PHRASE_DRIFT_TARGET_MS,
  READ_ALONG_TRUSTED_CONFIDENCE,
  READ_ALONG_WORD_DRIFT_TARGET_MS,
  detectReadAlongDrift,
  driftFromRange,
  highlightTimingSourceLabel,
  isTrustedWordTiming,
  timingRangeForCue,
  type ReadAlongDriftInput,
  type ReadAlongDriftReport,
  type TimingRange,
} from "./driftDetection";
export {
  HIGHLIGHT_MAP_V2_SCHEMA_VERSION,
  highlightMapV2TimingSourceLabel,
  highlightMapV2ToLegacyHighlightMap,
  isHighlightMapV2,
  legacyHighlightMapFromTimingArtifact,
  legacyTimingSourceFromV2,
  type HighlightMapV2,
  type HighlightMapV2Entry,
  type HighlightMapV2FallbackMode,
  type HighlightMapV2Summary,
  type HighlightMapV2TimingLevel,
  type HighlightMapV2TimingSource,
  type HighlightMapV2Traceability,
  type TimingArtifact,
} from "./highlightMapV2";
export {
  normalizeReadAlongVisualMode,
  readAlongHighlightClassName,
  readAlongHighlightDataAttributes,
  readAlongHighlightModeLabel,
  readAlongShouldHighlightBlock,
  readAlongShouldHighlightPhrase,
  readAlongShouldHighlightWord,
  readAlongVisualModeFromRuntime,
  type ReadAlongHighlightSurface,
  type ReadAlongHighlightVisualMode,
} from "./highlightVisualModes";
export {
  DEFAULT_READ_ALONG_PREFERENCES,
  GOLDEN_MINUTE_HIGHLIGHT_PREVIEW_TEXT,
  READ_ALONG_DEGRADED_SYNC_DISPLAY_OPTIONS,
  READ_ALONG_HIGHLIGHT_GRANULARITIES,
  READ_ALONG_HIGHLIGHT_STYLES,
  READ_ALONG_MACHINE_PREFERENCES_STORAGE_KEY,
  READ_ALONG_PREFERENCE_LABELS,
  READ_ALONG_PREFERENCE_SCOPES,
  READ_ALONG_PREFERENCES_SCOPE_STORAGE_KEY,
  READ_ALONG_SCROLL_FOLLOW_POLICIES,
  READ_ALONG_SYNC_STRICTNESS_OPTIONS,
  clearStoredReadAlongPreferences,
  effectiveReadAlongPreferences,
  loadReadAlongPreferences,
  normalizeReadAlongPreferences,
  readAlongCalibrationOffsetMs,
  readAlongPreferenceDataAttributes,
  readAlongProjectPreferencesStorageKey,
  readAlongVisualModeFromPreferences,
  saveReadAlongPreferences,
  type ReadAlongDegradedSyncDisplay,
  type ReadAlongHighlightGranularity,
  type ReadAlongHighlightStyle,
  type ReadAlongPreferenceScope,
  type ReadAlongPreferences,
  type ReadAlongScrollFollow,
  type ReadAlongSegmentBoundaryPreferences,
  type ReadAlongSyncStrictness,
} from "./readAlongPreferences";
export {
  readAlongRuntimeDebugRows,
  readAlongRuntimeStateLabel,
  readAlongRuntimeStatusClassName,
  type ReadAlongRuntimeDebugRow,
  type ReadAlongRuntimeSnapshot,
  type ReadAlongRuntimeState,
  type ReadAlongVisualMode,
} from "./readAlongState";
export {
  buildSpeechFluencyDiagnostics,
  type SpeechFluencyDiagnosticRow,
  type SpeechFluencyDiagnostics,
} from "./speechFluencyDiagnostics";
export {
  readAlongScrollPolicyDataAttributes,
  resolveReadAlongScrollPolicy,
  scrollReadAlongAnchor,
  type ReadAlongScrollDecision,
  type ReadAlongScrollDecisionInput,
  type ReadAlongScrollPolicy,
} from "./scrollFollowPolicy";
export {
  timingArtifactDebugRows,
  validateTimingArtifact,
  type TimingArtifactValidationInput,
  type TimingArtifactValidationIssue,
  type TimingArtifactValidationReport,
  type TimingArtifactValidationSeverity,
  type TimingArtifactValidationStatus,
} from "./timingArtifact";
export {
  evaluateBookReadAlongInvariant,
  evaluatePreparedSourceReadAlongInvariant,
  evaluateSourceSwitchInvariant,
  readAlongInvariantDebugRows,
  readAlongInvariantStatusLabel,
  type ReadAlongInvariantDebugRow,
  type ReadAlongInvariantIssue,
  type ReadAlongInvariantReport,
  type ReadAlongInvariantSeverity,
  type ReadAlongInvariantStatus,
  type ReadAlongInvariantSurface,
} from "./readAlongInvariant";
